language: go

go:
  - 1.2
  - tip

install:
  - go get -v -t ./...
  - go get github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=profile.cov ./...
  - goveralls -coverprofile=profile.cov -service=travis-ci
