language: go

go:
  - 1.2
  - tip

install:
  - go get -v -t ./...
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - export PATH=`echo $GOPATH | cut -d: -f1`/bin:$PATH
  - go test -v -covermode=count -coverprofile=profile.cov
  - goveralls -v -coverprofile=profile.cov -service=travis-ci
